### ISSUE TITLE
Did things change with this project, no longer works on Macbook?

### ISSUE THREAD

**Issue by Daksh** [DevXT-LLC/ezlocalai#24]
Hello,

I noticed that the project was named differently before and under a different GitHub account (and a different docker registry address). Is this only a change in name or does it mean that things are different and it is no longer the same tool?

Secondly, when I try to pull it on a Macbook with M2 Pro chip, I get this error:

```
➜  ~ docker pull joshxt/ezlocalai
Using default tag: latest
latest: Pulling from joshxt/ezlocalai
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Is this related to the change?

**Comment by Josh-XT** [comment]
Hello. I added some cloning TTS support and lost direct Mac support as result. You can still run it as x64 in Mac with some modifications to the docker compose file I believe. I don't use Mac OS, so I'm not 100% sure.

**Comment by Josh-XT** [comment]
Also, I moved the project under one of my organizations and renamed it after adding some additional functionality that required my orgs GitHub enterprise license to run the builds.

**Comment by Niraj81** [comment]
Yup not working for me as well, same issue.
