### ISSUE TITLE
Is there a endpoint I can invoke to download a certain model?

### ISSUE THREAD

**Issue by Daksh** [DevXT-LLC/ezlocalai#25]
I was facing this issue where in a new setup, my requests seemed to be not working or timing out. I figured (most likely) that it is because the model was not downloaded and my connection was not fast enough for it to happen quickly. What is the best way of using the endpoints? Is there an endpoint I can invoke first to download the required model and keep checking progress of the download?

**Comment by Josh-XT** [comment]
You can modify the `DEFAULT_MODEL` in your `.env` file to a different model name from the model list to have it download when the server starts.
