### ISSUE TITLE
Windows 10 - No NVIDIA GPU detected, using CPU image

### ISSUE THREAD

**Issue by SunixLiu** [DevXT-LLC/ezlocalai#36]
OS:Windows 10 Pro 22H2
nvcc --version:
(tg) PS C:\WINDOWS\system32> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

nvidia-smi:
(tg) PS C:\WINDOWS\system32> nvidia-smi
Thu Apr  4 22:39:13 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.99                 Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090      WDDM  | 00000000:65:00.0  On |                  N/A |
| 30%   51C    P8              33W / 350W |   9375MiB / 24576MiB |     11%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

when execute start.ps1, it told "unsupported operating system" and "No NVIDIA GPU detected, using CPU image.."
Test-NvidiaGpuPresent : Unsupported operating system
At D:\github\ezlocalai\start.ps1:52 char:5
+ if (Test-NvidiaGpuPresent) {
+     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Test-NvidiaGpuPresent

**Comment by Josh-XT** [comment]
You must run it with PowerShell 7+.

**Comment by SunixLiu** [comment]
I‘ve upgrade PowerShell, still got this "No NVIDIA GPU detected, using CPU image.."

PS D:\github\ezlocalai> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS D:\github\ezlocalai> .\start.ps1
Get-WmiObject: D:\github\ezlocalai\start.ps1:3
Line |
   3 |          $nvidiaPresent = Get-WmiObject Win32_VideoController | Where- …
     |                           ~~~~~~~~~~~~~
     | The term 'Get-WmiObject' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was
     | included, verify that the path is correct and try again.
No NVIDIA GPU detected, using CPU image..

**Comment by Josh-XT** [comment]
Very strange! Alternatively, you can use this to start it:

```bash
docker-compose -f docker-compose-cuda.yml down
docker-compose -f docker-compose-cuda.yml build
docker-compose -f docker-compose-cuda.yml up
```

**Comment by Josh-XT** [comment]
Updated the documentation to just remove the PowerShell script.
